#$('#page').addClass('container white-bg')
#$('#contact-page #page').addClass('container')
$('section#body_content').addClass('container')
$('#articles-page-page #page-container').addClass('container')
$('#articles-page-page #page-container #body_content').addClass('row')
